---
- hosts: all
  become: true
  become_method: sudo

  vars:
    easyrsa_user: vagrant
    easyrsa_dir: "/home/vagrant/ca"

  pre_tasks:
  - name: Include vars.yml
    include_vars:
      file: vars.yml

  roles:
    - andrelohmann.easy_rsa

  tasks:
  - name: read ca content
    set_fact:
      _ca: "{{lookup('file', easyrsa_dir+'/easy-rsa/keys/ca.crt') }}"

  - name: read ta content
    set_fact:
      _ta: "{{lookup('file', easyrsa_dir+'/easy-rsa/keys/ta.key') }}"

  - name: iterate clients
    include: client.yml
    with_items: "{{ easyrsa_clients }}"
    loop_control:
      loop_var: client
...
