---
- hosts: all
  become: true
  become_method: sudo

  vars:
    easyrsa_user: ubuntu
    easyrsa_dir: "/home/ubuntu/ca"

  pre_tasks:
  - name: Include vars.yml
    include_vars:
      file: vars.yml

  roles:
    - andrelohmann.easy_rsa
...
