---
- hosts: all
  become: true
  become_method: sudo

  vars:
    easyrsa_user: vagrant
    easyrsa_dir: "/home/vagrant/ca"

  pre_tasks:
  - name: check for file custom_vars.yml
    stat:
      path: custom_vars.yml
    register: stat_custom_vars
  - name: load custom vars, if existent
    include_vars:
      file: custom_vars.yml
    when: stat_custom_vars.stat.exists

  roles:
    - andrelohmann.easy_rsa

  tasks:
  - name: read ca content
    set_fact:
      _ca: "{{lookup('file', easyrsa_dir+'/easy-rsa/keys/ca.crt') }}"

  - name: read ta content
    set_fact:
      _ta: "{{lookup('file', easyrsa_dir+'/easy-rsa/keys/ta.key') }}"

  - name: iterate clients
    include: client.yml
    with_items: "{{ easyrsa_clients }}"
    loop_control:
      loop_var: client
...
